#!/bin/bash

set -e

cd /app
gem install --no-document bundler
bundle install --without development test

if ! gem spec passenger > /dev/null 2>&1; then
  gem install --no-document passenger
fi

rake assets:precompile
